/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorbiblioteca.view;

import gerenciadorbiblioteca.controle.ControlUtil;
import gerenciadorbiblioteca.controle.dao.EstanteDao;
import gerenciadorbiblioteca.controle.dao.LivroDao;
import gerenciadorbiblioteca.controle.dao.PrateleiraDao;
import gerenciadorbiblioteca.controle.dao.QuadrinhoDao;
import gerenciadorbiblioteca.controle.exceptions.ExceptionGeral;
import gerenciadorbiblioteca.model.Estante;
import gerenciadorbiblioteca.model.Livro;
import gerenciadorbiblioteca.model.LivrosTableModel;
import gerenciadorbiblioteca.model.Prateleira;
import gerenciadorbiblioteca.model.Quadrinho;
import gerenciadorbiblioteca.model.QuadrinhoTableModel;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Leonardo
 */
public class TelaInicial extends javax.swing.JFrame {
    
    LivrosTableModel livroTableModel = new LivrosTableModel();
    QuadrinhoTableModel quadrinhoTableModel = new QuadrinhoTableModel();
    ArrayList<Estante> estantes = new ArrayList<>();
    ArrayList<Prateleira> prateleiras = new ArrayList<>();
    
    ControlUtil ctrlUtil = new ControlUtil();
    
    LivroDao livroDao = new LivroDao();
    QuadrinhoDao quadrinhoDao = new QuadrinhoDao(); 
    PrateleiraDao prateleiraDao = new PrateleiraDao();
    EstanteDao estanteDao = new EstanteDao();
    ArrayList<Livro> livrosTabela = new ArrayList<>();
    ArrayList<Quadrinho> quadrinhosTabela = new ArrayList<>();
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() throws FileNotFoundException {
        livrosTabela = new ArrayList(livroDao.lerArquivo());
        quadrinhosTabela = new ArrayList(quadrinhoDao.lerArquivo());
        prateleiras = new ArrayList(prateleiraDao.lerArquivo());
        estantes = new ArrayList(estanteDao.lerArquivo());
        
        
        for(int i=0;i<livrosTabela.size();i++){
            livroTableModel.adcicionarLivro(livrosTabela.get(i));
        }
        for(int i=0;i<quadrinhosTabela.size();i++){
            quadrinhoTableModel.adcicionarQuadrinho(quadrinhosTabela.get(i));
        }     
        
        
        initComponents();
        jTableLivros.setModel(livroTableModel);
        jTableQuadrinhos.setModel(quadrinhoTableModel);
        
        for(int i=0;i<prateleiras.size();i++){
            prateleirasLivro.addItem(prateleiras.get(i).getNome());
            prateleirasQuadrinho.addItem(prateleiras.get(i).getNome());
        }
        for(int i=0;i<prateleiras.size();i++){
           selectEstantes.addItem(estantes.get(i).getNome());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeNovaEstante = new javax.swing.JTextField();
        txtNomeNovaPrateleira = new javax.swing.JTextField();
        txtNomeNovoLivro = new javax.swing.JTextField();
        selectEstantes = new javax.swing.JComboBox<>();
        prateleirasLivro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        btnCriarEst = new javax.swing.JButton();
        btnCriarPrat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cBCapaDura = new javax.swing.JCheckBox();
        txtNumeroPaginas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtISBNQuadrinho = new javax.swing.JTextField();
        txtGeneroQuadrinho = new javax.swing.JTextField();
        txtAutorQuadrinho = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableQuadrinhos = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNomeNovoLQuadrinho = new javax.swing.JTextField();
        cBColorido = new javax.swing.JCheckBox();
        prateleirasQuadrinho = new javax.swing.JComboBox<>();
        txtTipo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        btnNovoLivro = new javax.swing.JButton();
        btnCriarQuadrinho = new javax.swing.JButton();
        btnDeletarLivros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNomeNovaEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeNovaEstanteActionPerformed(evt);
            }
        });

        txtNomeNovoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeNovoLivroActionPerformed(evt);
            }
        });

        selectEstantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEstantesActionPerformed(evt);
            }
        });

        prateleirasLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prateleirasLivroActionPerformed(evt);
            }
        });

        jLabel1.setText("Nova Estante");

        jLabel2.setText("Nova Prateleira");

        jLabel3.setText("Novo Livro");

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        btnCriarEst.setText("Criar Estante");
        btnCriarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEstActionPerformed(evt);
            }
        });

        btnCriarPrat.setText("Criar Prateleira");
        btnCriarPrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarPratActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome");

        jLabel5.setText("Nome");

        jLabel6.setText("Titulo");

        jLabel7.setText("ISBN");

        jLabel8.setText("Autor");

        jLabel9.setText("Gênero");

        jLabel11.setText("Prateleira");

        jLabel12.setText("Estante");

        cBCapaDura.setText("Capa Dura");
        cBCapaDura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBCapaDuraActionPerformed(evt);
            }
        });

        jLabel13.setText("Número de Páginas");

        jLabel10.setText("Novo Quadrinho");

        txtISBNQuadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNQuadrinhoActionPerformed(evt);
            }
        });

        txtGeneroQuadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroQuadrinhoActionPerformed(evt);
            }
        });

        txtAutorQuadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorQuadrinhoActionPerformed(evt);
            }
        });

        jLabel14.setText("Titulo");

        jLabel15.setText("ISBN");

        jTableQuadrinhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableQuadrinhos);

        jLabel16.setText("Autor");

        jLabel17.setText("Gênero");

        jLabel18.setText("Prateleira");

        cBColorido.setText("Colorido");
        cBColorido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBColoridoActionPerformed(evt);
            }
        });

        prateleirasQuadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prateleirasQuadrinhoActionPerformed(evt);
            }
        });

        jLabel19.setText("Tipo");

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableLivros);

        btnNovoLivro.setText("Criar Livro");
        btnNovoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLivroActionPerformed(evt);
            }
        });

        btnCriarQuadrinho.setText("Criar Quadrinho");
        btnCriarQuadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarQuadrinhoActionPerformed(evt);
            }
        });

        btnDeletarLivros.setText("Deletar Livros Selecionado");
        btnDeletarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarLivrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeletarLivros)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtISBN)
                                            .addComponent(jLabel6)
                                            .addComponent(txtNomeNovoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtAutor)
                                                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(txtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cBCapaDura))))))
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnNovoLivro)
                                .addComponent(prateleirasLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtNomeNovaEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCriarEst))
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBNQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(txtNomeNovoLQuadrinho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAutorQuadrinho)
                                        .addComponent(txtGeneroQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cBColorido)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(prateleirasQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCriarQuadrinho)))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeNovaPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(selectEstantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCriarPrat))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeNovaPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectEstantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCriarPrat))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtISBNQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNovoLivro)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAutorQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeNovoLQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prateleirasQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtGeneroQuadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cBColorido)
                                            .addComponent(btnCriarQuadrinho)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel15)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeNovaEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCriarEst))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeNovoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prateleirasLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBCapaDura))))
                .addGap(16, 16, 16)
                .addComponent(btnDeletarLivros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectEstantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEstantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectEstantesActionPerformed

    private void txtNomeNovaEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeNovaEstanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeNovaEstanteActionPerformed

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void prateleirasLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prateleirasLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prateleirasLivroActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void cBCapaDuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBCapaDuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBCapaDuraActionPerformed

    private void txtISBNQuadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNQuadrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNQuadrinhoActionPerformed

    private void txtGeneroQuadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroQuadrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroQuadrinhoActionPerformed

    private void txtAutorQuadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorQuadrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorQuadrinhoActionPerformed

    private void prateleirasQuadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prateleirasQuadrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prateleirasQuadrinhoActionPerformed

    private void cBColoridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBColoridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBColoridoActionPerformed

    private void txtNomeNovoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeNovoLivroActionPerformed
    
    }//GEN-LAST:event_txtNomeNovoLivroActionPerformed

    private void btnNovoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLivroActionPerformed
        if((txtAutor.getText() != "") && txtGenero.getText() != "" && txtISBN.getText() != ""
                && txtNomeNovoLivro.getText() != "" && txtNumeroPaginas.getText() != ""){
            try {
                Livro livro = new Livro();
                livro.setTitulo(txtNomeNovoLivro.getText());
                livro.setAutor(txtAutor.getText());
                livro.setCapaDura(cBCapaDura.isSelected());
                livro.setGenero(txtGenero.getText());
                livro.setNumeroPaginas(Integer.parseInt(txtNumeroPaginas.getText()));
                livro.setPrateleira(prateleirasLivro.getSelectedItem().toString());
                livro.setISBN(txtISBN.getText());
                livro.setId(ctrlUtil.getIdIncr());
                
                livroDao.salvar(livro,true);
                livroTableModel.adcicionarLivro(livro);
                jTableLivros.addNotify();
                
                txtAutor.setText("");
                txtGenero.setText("");
                txtISBN.setText("");
                txtNomeNovoLivro.setText("");
                txtNumeroPaginas.setText("");
                
            } catch (ExceptionGeral ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }     
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoLivroActionPerformed

    private void btnCriarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEstActionPerformed
        if(txtNomeNovaEstante.getText() != null){
            try {
                Estante estante = new Estante();
                estante.setNome(txtNomeNovaEstante.getText());
                
                estanteDao.salvar(estante);
                estantes.add(estante);
                selectEstantes.addItem(estante.getNome());
                
                txtNomeNovaEstante.setText("");
            } catch (ExceptionGeral ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        }
    }//GEN-LAST:event_btnCriarEstActionPerformed

    private void btnCriarPratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarPratActionPerformed
        if(txtNomeNovaPrateleira.getText() != null){
            try {
                Prateleira prateleira = new Prateleira();
                prateleira.setNome(txtNomeNovaPrateleira.getText());
                prateleira.setEstante(selectEstantes.getSelectedItem().toString());
                
                prateleiraDao.salvar(prateleira);
                prateleiras.add(prateleira);
                
                prateleirasLivro.addItem(prateleira.getNome());
                prateleirasQuadrinho.addItem(prateleira.getNome());
                
                txtNomeNovaPrateleira.setText("");
            } catch (ExceptionGeral ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCriarPratActionPerformed

    private void btnCriarQuadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarQuadrinhoActionPerformed
        if((txtAutorQuadrinho.getText() == null) || (txtGeneroQuadrinho.getText() == null) || (txtISBNQuadrinho.getText() == null)
                || (txtNomeNovoLQuadrinho.getText() == null) || (txtTipo.getText() == null)){
        }
        else{
            try {
                Quadrinho quadrinho = new Quadrinho();
                
                quadrinho.setTitulo(txtNomeNovoLQuadrinho.getText());
                quadrinho.setAutor(txtAutorQuadrinho.getText());
                quadrinho.setColorido(cBColorido.isSelected());
                quadrinho.setGenero(txtGeneroQuadrinho.getText());
                quadrinho.setTipo(txtTipo.getText());
                quadrinho.setPrateleira(prateleirasQuadrinho.getSelectedItem().toString());
                quadrinho.setISBN(txtISBNQuadrinho.getText());
                quadrinho.setId(ctrlUtil.getIdIncr());
                
                quadrinhoDao.salvar(quadrinho);
                quadrinhoTableModel.adcicionarQuadrinho(quadrinho);
                jTableQuadrinhos.addNotify();
                
                txtAutorQuadrinho.setText("");
                txtGeneroQuadrinho.setText("");
                txtISBNQuadrinho.setText("");
                txtNomeNovoLQuadrinho.setText("");
                txtTipo.setText("");
                
            } catch (ExceptionGeral ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_btnCriarQuadrinhoActionPerformed

    private void btnDeletarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarLivrosActionPerformed
        int[] indiceLivrosSelecionados = jTableLivros.getSelectedRows();
        try {
            livroDao.deletar(indiceLivrosSelecionados);
        } catch (ExceptionGeral ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<indiceLivrosSelecionados.length;i++){
            livroTableModel.fireTableRowsDeleted(indiceLivrosSelecionados[i],indiceLivrosSelecionados[i] );
        }
        
        
        jTableLivros.addNotify();
        
    }//GEN-LAST:event_btnDeletarLivrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaInicial().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarEst;
    private javax.swing.JButton btnCriarPrat;
    private javax.swing.JButton btnCriarQuadrinho;
    private javax.swing.JButton btnDeletarLivros;
    private javax.swing.JButton btnNovoLivro;
    private javax.swing.JCheckBox cBCapaDura;
    private javax.swing.JCheckBox cBColorido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTable jTableQuadrinhos;
    private javax.swing.JComboBox<String> prateleirasLivro;
    private javax.swing.JComboBox<String> prateleirasQuadrinho;
    private javax.swing.JComboBox<String> selectEstantes;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAutorQuadrinho;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtGeneroQuadrinho;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtISBNQuadrinho;
    private javax.swing.JTextField txtNomeNovaEstante;
    private javax.swing.JTextField txtNomeNovaPrateleira;
    private javax.swing.JTextField txtNomeNovoLQuadrinho;
    private javax.swing.JTextField txtNomeNovoLivro;
    private javax.swing.JTextField txtNumeroPaginas;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
